{
 "title": "Current Best",
 "time": { "from": "2017-09-26T09:02:11.725Z", "to": "2019-10-05T00:30:46.702Z" },
 "panels": [
  {
   "title": "Gini",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "source": "data.csv", "target": "special:gini", "type": "timeseries" }
   ]
  },
  {
   "title": "Last Average PD",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "source": "data.csv", "target": "special:avg_PD", "type": "timeseries" }
   ]
  },
  {
   "title": "Average PD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "source": "data.csv", "target": "special:avg_PD", "type": "timeseries" }
   ]
  },
  {
   "title": "Rating Hist",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "source": "data.csv", "target": "rating", "type": "timeseries" }
   ]
  },
  {
   "title": "Default Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "source": "data.csv", "target": "special:default_rate", "type": "timeseries" }
   ]
  },
  {
   "title": "Agreement Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "source": "data.csv", "target": "special:agreement_count", "type": "timeseries" }
   ]
  }
 ]
}